#-------------------------------------------------
#
# Project created by QtCreator 2017-02-23T14:35:14
#
#-------------------------------------------------

# Build with Qt 5.12.10
# Mysql Database version is 5.7

# Deploy
# Windows
# windeployqt.exe c:\desktop\xx.exe
# D:\Source Codes\DaNet-Setup-2.4>windeployqt --release --qmldir "D:\Source Codes\DaNet" ./DaNet.exe
# copy libmysql.dll from Qt\Qt5.10.1\5.10.1\mingw53_32\bin\libmysql.dll
# open inno setup compiler...
# go on and give .exe file and include the folder
# target computer must have microsoft visual C++ redistributable package
#
# Linux
# https://github.com/probonopd/linuxdeployqt/releases
# rename the release to linuxdeployqt and copy to /usr/share/bin
# create folder for example danet and copy the binary named DaNet there.
# copy the icon named danet.png to the folder
# create danet.desktop file containing
#
# [Desktop Entry]
# Version=2.4.0
# Encoding=UTF-8
# Type=Application
# Name=DaNet
# Comment=DaNet
# Exec=/bin/DaNet/AppRun %f
# Icon=/bin/DaNet/DaNet.ico
#
# export PATH=/opt/Qt/5.12.10/gcc_64/bin/:$PATH
# linuxdeployqt ./Danet -appimage
# linuxdeployqt ./DaNet  -appimage -qmldir=/home/samad/share/programs/CPP/DaNet/
# copy all files and folders to /usr/bin/DaNet/
# locate appImage in /home/samad/.local/share/applications/DaNet.desktop




QT       += core gui sql printsupport xlsx quick qml

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TARGET = DaNet
TEMPLATE = app


# The following define makes your compiler emit warnings if you use
# any feature of Qt which as been marked as deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS \
            DANET_VER=\\\"2.4.0\\\" \
            ADMIN=\\\"samad\\\" \
            DEPARTMENT=\\\"tarahi\\\"

VERSION = $${DANET_VER}


# You can also make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0


SOURCES += main.cpp \
    backbone/backbone.cpp \
    backbone/startup/logindialog.cpp \
    backbone/startup/newrelease.cpp \
    lib/database/danetdbman.cpp \
    mainPanel/mainpanel.cpp \
    mainPanel/menu/admin/users/adduserdialog.cpp \
    mainPanel/menu/admin/users/edituserdialog.cpp \
    mainPanel/menu/admin/users/removeuserdialog.cpp \
    mainPanel/menu/admin/users/usermandialog.cpp \
    mainPanel/menu/help/about/aboutdialog2.cpp \
    mainPanel/menu/installation/exchangeSite/addexchangesitedialog.cpp \
    mainPanel/menu/installation/exchangeSite/editexchangesitedialog.cpp \
    mainPanel/menu/installation/exchangeSite/exchangesitemandialog.cpp \
    mainPanel/menu/installation/exchangeSite/removeexchangesitedialog.cpp \
    mainPanel/menu/installation/ODF/odfmandialog.cpp \
    mainPanel/menu/installation/ODF/addodfdialog.cpp \
    mainPanel/menu/installation/ODF/removeodfdialog.cpp \
    mainPanel/menu/installation/ODF/editodfdialog.cpp \
    mainPanel/menu/installation/ODF/addposdialog.cpp \
    mainPanel/menu/installation/ODF/removeposdialog.cpp \
    mainPanel/menu/installation/ODF/editposnodialog.cpp \
    mainPanel/menu/installation/device/deviceinstalldialog.cpp \
    mainPanel/menu/installation/device/adddeviceinstalldialog.cpp \
    mainPanel/menu/installation/device/removedeviceinstalldialog.cpp \
    mainPanel/menu/installation/device/editdevicepositiondialog.cpp \
    mainPanel/menu/installation/device/editdevicetypedialog.cpp \
    mainPanel/assigninterfacedialog.cpp \
    mainPanel/editinterfacedialog.cpp \
    mainPanel/emptyinterfacedialog.cpp \
    mainPanel/localdevicedialog.cpp \
    mainPanel/menu/management/DeviceManagement/addvlandialog.cpp \
    mainPanel/menu/management/DeviceManagement/addethertrunkdialog.cpp \
    mainPanel/menu/management/DeviceManagement/removevlandialog.cpp \
    mainPanel/menu/management/DeviceManagement/removeethertrunkdialog.cpp \
    mainPanel/menu/management/DeviceManagement/editvlandialog.cpp \
    mainPanel/menu/management/DeviceManagement/editethertrunkdialog.cpp \
    mainPanel/menu/management/DeviceManagement/devicemanagementdialog.cpp \
    mainPanel/menu/management/ODFManagement/odfmanagementdialog.cpp \
    mainPanel/menu/management/ODFManagement/assignodfpindialog.cpp \
    mainPanel/menu/management/ODFManagement/editodfpindialog.cpp \
    mainPanel/menu/management/ODFManagement/depleteodfpindialog.cpp \
    mainPanel/menu/management/DeviceManagement/addvpndialog.cpp \
    mainPanel/menu/management/DeviceManagement/editvpndialog.cpp \
    mainPanel/menu/management/DeviceManagement/removevpndialog.cpp \
    lib/netTools/nettools.cpp \
    mainPanel/menu/management/commodities/cat/cat_addedit.cpp \
    mainPanel/menu/management/commodities/cat/cat_dialog.cpp \
    mainPanel/menu/management/commodities/commodity/comm_dialog.cpp \
    mainPanel/menu/management/commodities/commodity/comm_addedit.cpp \
    mainPanel/menu/management/commodities/commodity/comm_remove.cpp \
    mainPanel/menu/management/commodities/cat/cat_remove.cpp \
    mainPanel/menu/management/commodities/usage/usage_addedit.cpp \
    mainPanel/menu/management/commodities/usage/usage_dialog.cpp \
    mainPanel/menu/management/commodities/usage/usage_remove.cpp \
    mainPanel/menu/management/letters/letteraddeditdialog.cpp \
    mainPanel/menu/management/letters/letterremovedialog.cpp \
    mainPanel/menu/management/letters/lettersdialog.cpp \
    mainPanel/menu/management/letters/letterviewdialog.cpp \
    mainPanel/menu/management/purchases/purchasemandialog.cpp \
    mainPanel/menu/management/purchases/addpurchasedialog.cpp \
    mainPanel/menu/management/purchases/editpurchasedialog.cpp \
    mainPanel/menu/management/purchases/removepurchasedialog.cpp \
    mainPanel/menu/management/devices/adddevicedialog.cpp \
    mainPanel/menu/management/devices/devicemandialog.cpp \
    mainPanel/menu/management/devices/editdevicedialog.cpp \
    mainPanel/menu/management/devices/removedevicedialog.cpp \
    mainPanel/menu/management/cards/addcarddialog.cpp \
    mainPanel/menu/management/cards/cardmandialog.cpp \
    mainPanel/menu/management/cards/editcarddialog.cpp \
    mainPanel/menu/management/cards/removecarddialog.cpp \
    mainPanel/menu/management/telephones/telephoneaddeditdialog.cpp \
    mainPanel/menu/management/telephones/telephoneremovedialog.cpp \
    mainPanel/menu/management/telephones/telephonesdialog.cpp \
    mainPanel/menu/management/telephones/telephoneviewdialog.cpp \
    mainPanel/menu/management/uninstalled/uninstalledaddeditdialog.cpp \
    mainPanel/menu/management/uninstalled/uninstalleddialog.cpp \
    mainPanel/menu/management/uninstalled/uninstalledremovedialog.cpp \
    mainPanel/menu/plan/ipv4/subnet2/subnet2v4pooldialog.cpp \
    mainPanel/menu/plan/ipv4/subnet2/subnet2v4assignmentdialog.cpp \
    mainPanel/menu/plan/ipv4/subnet2/subnet2v4releasedialog.cpp \
    mainPanel/menu/plan/ipv4/ip/ipv4pooldialog.cpp \
    mainPanel/menu/plan/ipv4/ip/ipv4assigndialog.cpp \
    mainPanel/menu/plan/ipv4/ip/ipv4releasedialog.cpp \
    mainPanel/menu/plan/ipv4/ip/addipv4pooldialog.cpp \
    mainPanel/menu/plan/ipv4/ip/removeipv4pooldialog.cpp \
    mainPanel/menu/plan/connection/editbrasaggdialog.cpp \
    mainPanel/menu/plan/connection/removebrasaggdialog.cpp \
    mainPanel/menu/plan/connection/addbrasaggdialog.cpp \
    mainPanel/menu/plan/connection/connectiondialog.cpp \
    mainPanel/menu/plan/connection/addaggcxdialog.cpp \
    mainPanel/menu/plan/connection/editaggcxdialog.cpp \
    mainPanel/menu/plan/connection/removeaggcxdialog.cpp \
    mainPanel/menu/plan/dslam/dslamdialog.cpp \
    mainPanel/menu/plan/dslam/dslam5600/dslamma5600widget.cpp \
    mainPanel/menu/plan/dslam/dslam5616/dslamma5616widget.cpp \
    mainPanel/menu/plan/dslam/dslam5600/ma5600plandialog.cpp \
    mainPanel/menu/plan/dslam/dslam5600/ma5600brasplandialog.cpp \
    mainPanel/menu/plan/dslam/dslam5600/ma5600singleaggbrasplandialog.cpp \
    mainPanel/menu/plan/dslam/dslam5600/ma5600removeplandialog.cpp \
    mainPanel/menu/plan/dslam/dslam5600/ma5600aggmetroplandialog.cpp \
    mainPanel/menu/plan/dslam/dslam5600/ma5600singleaggmetroplandialog.cpp \
    mainPanel/menu/plan/dslam/dslam5600/ma5600removebrasplandialog.cpp \
    mainPanel/menu/plan/dslam/dslam5600/ma5600removeaggmetroplandialog.cpp \
    mainPanel/menu/plan/dslam/dslam5616/ma5616plandialog.cpp \
    mainPanel/menu/plan/dslam/dslam5616/ma5616removeplandialog.cpp \
    mainPanel/menu/plan/dslam/dslam5616/ma5616removeaggmetroplandialog.cpp \
    mainPanel/menu/plan/dslam/dslam5616/ma5616removebrasplandialog.cpp \
    mainPanel/menu/plan/dslam/dslam5616/ma5616aggmetroplandialog.cpp \
    mainPanel/menu/plan/dslam/dslam5616/ma5616brasplandialog.cpp \
    mainPanel/menu/plan/dslam/dslam5616/ma5616singleaggbrasplandialog.cpp \
    mainPanel/menu/management/modules/editmodulesdialog.cpp \
    mainPanel/menu/management/modules/removemoduledialog.cpp \
    mainPanel/menu/management/modules/modulesmandialog.cpp \
    mainPanel/menu/management/modules/addmoduledialog.cpp \
    mainPanel/menu/plan/accessSingleSwitch/accesssingleswitchdialog.cpp \
    mainPanel/menu/plan/accessDoubleSwitch/accessdoubleswitchdialog.cpp \
    mainPanel/menu/plan/accessBrasConfig/accessbrasconfigdialog.cpp \
    mainPanel/menu/plan/NAS/brasnasipmandialog.cpp \
    mainPanel/menu/plan/NAS/editnasipdialog.cpp \
    mainPanel/menu/plan/NAS/removenasipdialog.cpp \
    mainPanel/menu/plan/NAS/addnasipdialog.cpp \
    mainPanel/menu/installation/card/cardinstalldialog.cpp \
    mainPanel/menu/installation/card/adddevicecarddialog.cpp \
    mainPanel/menu/installation/card/removedevicecarddialog.cpp \
    mainPanel/changemoduledialog.cpp \
    mainPanel/menu/plan/SBCIpLB/sbciploopbackdialog.cpp \
    mainPanel/exchangeinfodialog.cpp \
    mainPanel/menu/report/interface/interfacereportdialog.cpp \
    lib/report/interface/ReportInterface.cpp \
    mainPanel/menu/report/lom/lomitemdialog.cpp \
    mainPanel/menu/report/odf/odfreportdialog.cpp \
    lib/report/odf/ReportOdf.cpp \
    mainPanel/exportpdfdialog.cpp \
    mainPanel/menu/plan/commercial/reservetocommercialdialog.cpp \
    mainPanel/menu/report/sites/exchangesitesreportdialog.cpp \
    lib/report/sites/ReportSites.cpp \
    lib/report/floorplan/TL/ReportFloorPlanTL.cpp \
    mainPanel/menu/report/floorplan/floorplanreportdialog.cpp \
    mainPanel/menu/report/device/reportdevicedialog.cpp \
    lib/report/device/ReportDevice.cpp \
    mainPanel/menu/report/ipv4plan/net/reportnetworkv4dialog.cpp \
    mainPanel/menu/report/ipv4plan/subnet/reportsubnetv4dialog.cpp \
    mainPanel/menu/report/ipv4plan/ip/reportipv4dialog.cpp \
    lib/report/ipv4plan/net/ReportNetworkIpV4Plan.cpp \
    lib/report/ipv4plan/subnet/ReportSubnetIpV4Plan.cpp \
    lib/report/ipv4plan/ip/ReportIpV4Plan.cpp \
    mainPanel/menu/tools/NetworkCalculator/networkcalculatordialog.cpp \
    mainPanel/menu/report/DSLAM/reportdslamdialog.cpp \
    lib/report/DSLAM/ReportDSLAM.cpp \
    mainPanel/menu/tools/ipPoolAnalyser/ippoolanalyserdialog.cpp \
    mainPanel/menu/tools/ConfigurationAnalyser/configurationanalyserdialog.cpp \
    mainPanel/menu/tools/NetworkAssistant/networkassistantdialog.cpp \
    mainPanel/menu/log/recentLog/recentlogdialog.cpp \
    mainPanel/menu/profile/profiledialog.cpp \
    mainPanel/menu/help/about/aboutdialog.cpp \
    mainPanel/menu/help/recommendation/recommendationdialog.cpp \
    mainPanel/menu/admin/recommendations/recommendationsviewdialog.cpp \
    mainPanel/menu/admin/recommendations/removerecommendationdialog.cpp \
    mainPanel/menu/report/commercial/reportreservetocommercialdialog.cpp \
    mainPanel/menu/admin/log/clearlogdialog.cpp \
    lib/report/floorplan/TR/ReportFloorPlanTR.cpp \
    lib/report/floorplan/BL/ReportFloorPlanBL.cpp \
    lib/report/floorplan/BR/ReportFloorPlanBR.cpp \
    mainPanel/menu/report/lom/lomdialog.cpp \
    lib/report/lom/Reportlom.cpp \
    mainPanel/menu/plan/ipv4/subnet2/splitsubnet2v4dialog.cpp \
    mainPanel/menu/plan/ipv4/subnet2/mergesubnet2v4dialog.cpp \
    mainPanel/menu/plan/ipv4/net/addnetv4dialog.cpp \
    mainPanel/menu/plan/ipv4/net/editnetv4dialog.cpp \
    mainPanel/menu/plan/ipv4/net/netv4assignmentdialog.cpp \
    mainPanel/menu/plan/ipv4/net/netv4pooldialog.cpp \
    mainPanel/menu/plan/ipv4/net/removenetv4dialog.cpp \
    mainPanel/menu/plan/ipv4/subnet3/mergesubnet3v4dialog.cpp \
    mainPanel/menu/plan/ipv4/subnet3/splitsubnet3v4dialog.cpp \
    mainPanel/menu/plan/ipv4/subnet3/subnet3v4assignmentdialog.cpp \
    mainPanel/menu/plan/ipv4/subnet3/subnet3v4pooldialog.cpp \
    mainPanel/menu/plan/ipv4/subnet3/subnet3v4releasedialog.cpp \
    mainPanel/menu/plan/ipv4/subnet1/mergesubnet1v4dialog.cpp \
    mainPanel/menu/plan/ipv4/subnet1/splitsubnet1v4dialog.cpp \
    mainPanel/menu/plan/ipv4/subnet1/subnet1v4assignmentdialog.cpp \
    mainPanel/menu/plan/ipv4/subnet1/subnet1v4pooldialog.cpp \
    mainPanel/menu/plan/ipv4/subnet1/subnet1v4releasedialog.cpp \
    mainPanel/menu/plan/ipv4/net/subnetv4searchdialog.cpp \
    lib/report/exchange/ReportExchange.cpp \
    mainPanel/menu/plan/vlanRef/addvlanrefdialog.cpp \
    mainPanel/menu/plan/vlanRef/editvlanrefdialog.cpp \
    mainPanel/menu/plan/vlanRef/removevlanrefdialog.cpp \
    mainPanel/menu/plan/vlanRef/vlanrefdialog.cpp \
    mainPanel/menu/plan/vsiRef/addvsirefdialog.cpp \
    mainPanel/menu/plan/vsiRef/editvsirefdialog.cpp \
    mainPanel/menu/plan/vsiRef/removevsirefdialog.cpp \
    mainPanel/menu/plan/vsiRef/vsirefdialog.cpp \
    mainPanel/menu/plan/rdRef/addrdrefdialog.cpp \
    mainPanel/menu/plan/rdRef/editrdrefdialog.cpp \
    mainPanel/menu/plan/rdRef/rdrefdialog.cpp \
    mainPanel/menu/plan/rdRef/removerdrefdialog.cpp \
    mainPanel/menu/plan/pvcRef/addpvcrefdialog.cpp \
    mainPanel/menu/plan/pvcRef/editpvcrefdialog.cpp \
    mainPanel/menu/plan/pvcRef/pvcrefdialog.cpp \
    mainPanel/menu/plan/pvcRef/removepvcrefdialog.cpp \
    mainPanel/menu/plan/dslam/dslam5616/dslamma5616portdescdialog.cpp \
    mainPanel/menu/plan/dslam/dslam5600/dslamma5600portdescdialog.cpp \
    lib/report/general/Report.cpp \
    mainPanel/menu/plan/dslam/dslammxk819/dslammxk819widget.cpp \
    mainPanel/menu/plan/dslam/dslammxk819/dslammxk819portdescdialog.cpp \
    mainPanel/menu/plan/dslam/dslammxk819/mxk819aggmetroplandialog.cpp \
    mainPanel/menu/plan/dslam/dslammxk819/mxk819singleaggmetroplandialog.cpp \
    mainPanel/menu/plan/dslam/dslammxk819/mxk819brasplandialog.cpp \
    mainPanel/menu/plan/dslam/dslammxk819/mxk819singleaggbrasplandialog.cpp \
    mainPanel/menu/plan/dslam/dslammxk819/mxk819plandialog.cpp \
    mainPanel/menu/plan/dslam/dslammxk819/mxk819removeaggmetroplandialog.cpp \
    mainPanel/menu/plan/dslam/dslammxk819/mxk819removebrasplandialog.cpp \
    mainPanel/menu/plan/dslam/dslammxk819/mxk819removeplandialog.cpp \
    mainPanel/menu/tools/NetworkAssistant/configWidgets/sysnamewidget.cpp \
    mainPanel/menu/tools/NetworkAssistant/configWidgets/batchvlanwidget.cpp \
    mainPanel/menu/tools/NetworkAssistant/configWidgets/vlanwidget.cpp \
    mainPanel/menu/tools/NetworkAssistant/configWidgets/interfacewidget.cpp \
    mainPanel/menu/tools/NetworkAssistant/configWidgets/portswitchwidget.cpp \
    mainPanel/menu/tools/NetworkAssistant/configWidgets/linktypewidget.cpp \
    mainPanel/menu/tools/NetworkAssistant/configWidgets/trunkwidget.cpp \
    mainPanel/menu/tools/NetworkAssistant/configWidgets/loadbalacewidget.cpp \
    mainPanel/menu/tools/NetworkAssistant/configWidgets/allowpasswidget.cpp \
    mainPanel/menu/tools/NetworkAssistant/configWidgets/defaultvlanwidget.cpp \
    mainPanel/menu/tools/NetworkAssistant/configWidgets/hybridportwidget.cpp \
    mainPanel/menu/tools/NetworkAssistant/configWidgets/mapvlanwidget.cpp \
    mainPanel/menu/tools/NetworkAssistant/configWidgets/ipassignwidget.cpp \
    mainPanel/menu/tools/NetworkAssistant/configWidgets/bindvpnwidget.cpp \
    mainPanel/menu/tools/NetworkAssistant/configWidgets/dot1qtagwidget.cpp \
    mainPanel/menu/tools/NetworkAssistant/configWidgets/qinqwidget.cpp \
    mainPanel/menu/tools/NetworkAssistant/configWidgets/vpninstancewidget.cpp \
    mainPanel/menu/tools/NetworkAssistant/configWidgets/routewidget.cpp \
    mainPanel/deviceWidgets/S9303/s9303widget.cpp \
    mainPanel/deviceWidgets/S9306/s9306widget.cpp \
    mainPanel/deviceWidgets/S5300/s5300widget.cpp \
    mainPanel/deviceWidgets/ME60X16/me60x16widget.cpp \
    mainPanel/deviceWidgets/ME60X8/me60x8widget.cpp \
    mainPanel/deviceWidgets/NE5000X16/ne5000X16widget.cpp \
    mainPanel/deviceWidgets/NE5000X16A/ne5000X16Awidget.cpp \
    mainPanel/deviceWidgets/NE40X16/ne40x16widget.cpp \
    mainPanel/deviceWidgets/NE40X8/ne40x8widget.cpp \
    mainPanel/deviceWidgets/CX200/cx200widget.cpp \
    mainPanel/deviceWidgets/S2403H/s2403hwidget.cpp \
    mainPanel/deviceWidgets/ASR9010/asr9010widget.cpp \
    mainPanel/deviceWidgets/ASR1002/asr1002widget.cpp \
    mainPanel/deviceWidgets/ASR1013/asr1013widget.cpp \
    mainPanel/deviceWidgets/C7613/c7613widget.cpp \
    mainPanel/deviceWidgets/DSLAM16S/dslam16swidget.cpp \
    mainPanel/deviceWidgets/DSLAM4S/dslam4swidget.cpp \
    mainPanel/menu/installation/card/odfpinrequestdialog.cpp \
    mainPanel/menu/installation/device/editdevicedescdialog.cpp \
    mainPanel/menu/installation/device/editdevicepurchasedialog.cpp \
    mainPanel/menu/installation/card/changedslamcarddialog.cpp \
    mainPanel/menu/installation/card/editcarddescdialog.cpp \
    mainPanel/menu/installation/card/editcardpurchasedialog.cpp \
    mainPanel/menu/stat/exchangesstatdialog.cpp \
    mainPanel/menu/stat/portsstatdialog.cpp \
    mainPanel/menu/stat/cardstatdialog.cpp \
    mainPanel/menu/plan/dslam/dslamaddnewvlandialog.cpp \
    mainPanel/menu/report/DSLAM/reporttotaldslamplandialog.cpp \
    mainPanel/menu/plan/dslam/newSitePlan/newsitedslamdialog.cpp \
    mainPanel/menu/plan/dslam/localNewDslam/localnewdslamdialog.cpp \
    mainPanel/menu/stat/devicecountdialog.cpp \
    mainPanel/menu/stat/devicesstatdialog.cpp \
    mainPanel/changeinterfaceodfdialog.cpp \
    mainPanel/OdfAssignDetach/assigninterfaceodfdialog.cpp \
    mainPanel/OdfAssignDetach/detachinterfaceodfdialog.cpp \
    mainPanel/menu/installation/card/portbyportodfrequestdialog.cpp \
    mainPanel/exportexceldialog.cpp \
    mainPanel/menu/management/saloon/saloonmandialog.cpp \
    mainPanel/menu/management/saloon/removesaloondialog.cpp \
    mainPanel/menu/management/saloon/editsaloondialog.cpp \
    mainPanel/menu/management/saloon/addsaloondialog.cpp \
    mainPanel/menu/tools/ModuleAnalyser/moduleanalyserdialog.cpp \
    backbone/startup/outofservice.cpp \
    mainPanel/menu/installation/device/editdevicenamedialog.cpp \
    mainPanel/menu/management/interfaceType/addinterfacetypedialog.cpp \
    mainPanel/menu/management/interfaceType/editinterfacetypedialog.cpp \
    mainPanel/menu/management/interfaceType/interfacetypedialog.cpp \
    mainPanel/menu/management/interfaceType/removeinterfacetypedialog.cpp \
    mainPanel/changeinterfacetypedialog.cpp \
    mainPanel/menu/help/regexHelp/regexphelpdialog.cpp \
    mainPanel/menu/plan/dslam/removeDslam/removedslamdialog.cpp \
    lib/report/DSLAM/RemoveDSLAM.cpp
HEADERS  += \
    backbone/backbone.h \
    backbone/startup/logindialog.h \
    backbone/startup/newrelease.h \
    lib/database/danetdbman.h \
    lib/headerview.h \
    lib/sortfilterproxymodel.h \
    mainPanel/mainpanel.h \
    mainPanel/menu/admin/users/adduserdialog.h \
    mainPanel/menu/admin/users/edituserdialog.h \
    mainPanel/menu/admin/users/removeuserdialog.h \
    mainPanel/menu/admin/users/usermandialog.h \
    mainPanel/menu/help/about/aboutdialog2.h \
    mainPanel/menu/installation/exchangeSite/addexchangesitedialog.h \
    mainPanel/menu/installation/exchangeSite/editexchangesitedialog.h \
    mainPanel/menu/installation/exchangeSite/exchangesitemandialog.h \
    mainPanel/menu/installation/exchangeSite/removeexchangesitedialog.h \
    mainPanel/menu/installation/ODF/odfmandialog.h \
    mainPanel/menu/installation/ODF/addodfdialog.h \
    mainPanel/menu/installation/ODF/removeodfdialog.h \
    mainPanel/menu/installation/ODF/editodfdialog.h \
    mainPanel/menu/installation/ODF/addposdialog.h \
    mainPanel/menu/installation/ODF/removeposdialog.h \
    mainPanel/menu/installation/ODF/editposnodialog.h \
    mainPanel/menu/installation/device/deviceinstalldialog.h \
    mainPanel/menu/installation/device/adddeviceinstalldialog.h \
    mainPanel/menu/installation/device/removedeviceinstalldialog.h \
    mainPanel/menu/installation/device/editdevicepositiondialog.h \
    mainPanel/menu/installation/device/editdevicetypedialog.h \
    mainPanel/assigninterfacedialog.h \
    mainPanel/editinterfacedialog.h \
    mainPanel/emptyinterfacedialog.h \
    mainPanel/localdevicedialog.h \
    mainPanel/menu/management/DeviceManagement/addvlandialog.h \
    mainPanel/menu/management/DeviceManagement/addethertrunkdialog.h \
    mainPanel/menu/management/DeviceManagement/removevlandialog.h \
    mainPanel/menu/management/DeviceManagement/removeethertrunkdialog.h \
    mainPanel/menu/management/DeviceManagement/editvlandialog.h \
    mainPanel/menu/management/DeviceManagement/editethertrunkdialog.h \
    mainPanel/menu/management/DeviceManagement/devicemanagementdialog.h \
    mainPanel/menu/management/ODFManagement/odfmanagementdialog.h \
    lib/mapmodel.h \
    lib/centeralignedmodel.h \
    lib/interfacemodel.h \
    mainPanel/menu/management/ODFManagement/assignodfpindialog.h \
    mainPanel/menu/management/ODFManagement/editodfpindialog.h \
    mainPanel/menu/management/ODFManagement/depleteodfpindialog.h \
    mainPanel/menu/management/DeviceManagement/addvpndialog.h \
    mainPanel/menu/management/DeviceManagement/editvpndialog.h \
    mainPanel/menu/management/DeviceManagement/removevpndialog.h \
    lib/netTools/nettools.h \
    mainPanel/menu/management/commodities/cat/cat_addedit.h \
    mainPanel/menu/management/commodities/cat/cat_dialog.h \
    mainPanel/menu/management/commodities/commodity/comm_dialog.h \
    mainPanel/menu/management/commodities/commodity/comm_addedit.h \
    mainPanel/menu/management/commodities/commodity/comm_remove.h \
    mainPanel/menu/management/commodities/cat/cat_remove.h \
    mainPanel/menu/management/commodities/usage/usage_addedit.h \
    mainPanel/menu/management/commodities/usage/usage_dialog.h \
    mainPanel/menu/management/commodities/usage/usage_remove.h \
    mainPanel/menu/management/letters/letteraddeditdialog.h \
    mainPanel/menu/management/letters/letterremovedialog.h \
    mainPanel/menu/management/letters/lettersdialog.h \
    mainPanel/menu/management/letters/letterviewdialog.h \
    mainPanel/menu/management/purchases/purchasemandialog.h \
    mainPanel/menu/management/purchases/addpurchasedialog.h \
    mainPanel/menu/management/purchases/editpurchasedialog.h \
    mainPanel/menu/management/purchases/removepurchasedialog.h \
    mainPanel/menu/management/devices/adddevicedialog.h \
    mainPanel/menu/management/devices/devicemandialog.h \
    mainPanel/menu/management/devices/editdevicedialog.h \
    mainPanel/menu/management/devices/removedevicedialog.h \
    mainPanel/menu/management/cards/addcarddialog.h \
    mainPanel/menu/management/cards/cardmandialog.h \
    mainPanel/menu/management/cards/editcarddialog.h \
    mainPanel/menu/management/cards/removecarddialog.h \
    mainPanel/menu/management/telephones/telephoneaddeditdialog.h \
    mainPanel/menu/management/telephones/telephoneremovedialog.h \
    mainPanel/menu/management/telephones/telephonesdialog.h \
    mainPanel/menu/management/telephones/telephoneviewdialog.h \
    mainPanel/menu/management/uninstalled/uninstalledaddeditdialog.h \
    mainPanel/menu/management/uninstalled/uninstalleddialog.h \
    mainPanel/menu/management/uninstalled/uninstalledremovedialog.h \
    mainPanel/menu/plan/ipv4/subnet2/subnet2v4pooldialog.h \
    mainPanel/menu/plan/ipv4/subnet2/subnet2v4assignmentdialog.h \
    mainPanel/menu/plan/ipv4/subnet2/subnet2v4releasedialog.h \
    mainPanel/menu/plan/ipv4/ip/ipv4pooldialog.h \
    mainPanel/menu/plan/ipv4/ip/ipv4assigndialog.h \
    mainPanel/menu/plan/ipv4/ip/ipv4releasedialog.h \
    mainPanel/menu/plan/ipv4/ip/addipv4pooldialog.h \
    mainPanel/menu/plan/ipv4/ip/removeipv4pooldialog.h \
    mainPanel/menu/plan/connection/editbrasaggdialog.h \
    mainPanel/menu/plan/connection/removebrasaggdialog.h \
    mainPanel/menu/plan/connection/addbrasaggdialog.h \
    mainPanel/menu/plan/connection/connectiondialog.h \
    mainPanel/menu/plan/connection/addaggcxdialog.h \
    mainPanel/menu/plan/connection/editaggcxdialog.h \
    mainPanel/menu/plan/connection/removeaggcxdialog.h \
    mainPanel/menu/plan/dslam/dslamdialog.h \
    mainPanel/menu/plan/dslam/dslam5600/dslamma5600widget.h \
    mainPanel/menu/plan/dslam/dslam5616/dslamma5616widget.h \
    mainPanel/menu/plan/dslam/dslam5600/ma5600plandialog.h \
    mainPanel/menu/plan/dslam/dslam5600/ma5600brasplandialog.h \
     mainPanel/menu/plan/dslam/dslam5600/ma5600singleaggbrasplandialog.h \
    mainPanel/menu/plan/dslam/dslam5600/ma5600removeplandialog.h \
    mainPanel/menu/plan/dslam/dslam5600/ma5600aggmetroplandialog.h \
    mainPanel/menu/plan/dslam/dslam5600/ma5600singleaggmetroplandialog.h \
    mainPanel/menu/plan/dslam/dslam5600/ma5600removebrasplandialog.h \
    mainPanel/menu/plan/dslam/dslam5600/ma5600removeaggmetroplandialog.h \
    mainPanel/menu/plan/dslam/dslam5616/ma5616plandialog.h \
    mainPanel/menu/plan/dslam/dslam5616/ma5616removeplandialog.h \
    mainPanel/menu/plan/dslam/dslam5616/ma5616removeaggmetroplandialog.h \
    mainPanel/menu/plan/dslam/dslam5616/ma5616removebrasplandialog.h \
    mainPanel/menu/plan/dslam/dslam5616/ma5616aggmetroplandialog.h \
    mainPanel/menu/plan/dslam/dslam5616/ma5616brasplandialog.h \
    mainPanel/menu/plan/dslam/dslam5616/ma5616singleaggbrasplandialog.h \
    mainPanel/menu/management/modules/editmodulesdialog.h \
    mainPanel/menu/management/modules/removemoduledialog.h \
    mainPanel/menu/management/modules/modulesmandialog.h \
    mainPanel/menu/management/modules/addmoduledialog.h \
    mainPanel/menu/plan/accessSingleSwitch/accesssingleswitchdialog.h \
    mainPanel/menu/plan/accessDoubleSwitch/accessdoubleswitchdialog.h \
    mainPanel/menu/plan/accessBrasConfig/accessbrasconfigdialog.h \
    mainPanel/menu/plan/NAS/brasnasipmandialog.h \
    mainPanel/menu/plan/NAS/editnasipdialog.h \
    mainPanel/menu/plan/NAS/removenasipdialog.h \
    mainPanel/menu/plan/NAS/addnasipdialog.h \
    mainPanel/menu/installation/card/cardinstalldialog.h \
    mainPanel/menu/installation/card/adddevicecarddialog.h \
    mainPanel/menu/installation/card/removedevicecarddialog.h \
    mainPanel/changemoduledialog.h \
    mainPanel/menu/plan/SBCIpLB/sbciploopbackdialog.h \
    mainPanel/exchangeinfodialog.h \
    mainPanel/menu/report/interface/interfacereportdialog.h \
    lib/report/interface/ReportInterface.h \
    mainPanel/menu/report/lom/lomitemdialog.h \
    mainPanel/menu/report/odf/odfreportdialog.h \
    lib/report/odf/ReportOdf.h \
    mainPanel/exportpdfdialog.h \
    mainPanel/menu/plan/commercial/reservetocommercialdialog.h \
    mainPanel/menu/report/sites/exchangesitesreportdialog.h \
    lib/report/sites/ReportSites.h \
    lib/report/floorplan/TL/ReportFloorPlanTL.h \
    mainPanel/menu/report/floorplan/floorplanreportdialog.h \
    mainPanel/menu/report/device/reportdevicedialog.h \
    lib/report/device/ReportDevice.h \
    mainPanel/menu/report/ipv4plan/net/reportnetworkv4dialog.h \
    mainPanel/menu/report/ipv4plan/subnet/reportsubnetv4dialog.h \
    mainPanel/menu/report/ipv4plan/ip/reportipv4dialog.h \
    lib/report/ipv4plan/net/ReportNetworkIpV4Plan.h \
    lib/report/ipv4plan/subnet/ReportSubnetIpV4Plan.h \
    lib/report/ipv4plan/ip/ReportIpV4Plan.h \
    mainPanel/menu/tools/NetworkCalculator/networkcalculatordialog.h \
    mainPanel/menu/report/DSLAM/reportdslamdialog.h \
    lib/report/DSLAM/ReportDSLAM.h \
    mainPanel/menu/tools/ipPoolAnalyser/ippoolanalyserdialog.h \
    mainPanel/menu/tools/ConfigurationAnalyser/configurationanalyserdialog.h \
    mainPanel/menu/tools/NetworkAssistant/networkassistantdialog.h \
    mainPanel/menu/log/recentLog/recentlogdialog.h \
    mainPanel/menu/profile/profiledialog.h \
    mainPanel/menu/help/about/aboutdialog.h \
    mainPanel/menu/help/recommendation/recommendationdialog.h \
    mainPanel/menu/admin/recommendations/recommendationsviewdialog.h \
    mainPanel/menu/admin/recommendations/removerecommendationdialog.h \
    mainPanel/menu/report/commercial/reportreservetocommercialdialog.h \
    mainPanel/menu/admin/log/clearlogdialog.h \
    lib/report/floorplan/TR/ReportFloorPlanTR.h \
    lib/report/floorplan/BL/ReportFloorPlanBL.h \
    lib/report/floorplan/BR/ReportFloorPlanBR.h \
    mainPanel/menu/report/lom/lomdialog.h \
    lib/report/lom/Reportlom.h \
    mainPanel/menu/plan/ipv4/subnet2/splitsubnet2v4dialog.h \
    mainPanel/menu/plan/ipv4/subnet2/mergesubnet2v4dialog.h \
    mainPanel/menu/plan/ipv4/net/addnetv4dialog.h \
    mainPanel/menu/plan/ipv4/net/editnetv4dialog.h \
    mainPanel/menu/plan/ipv4/net/netv4assignmentdialog.h \
    mainPanel/menu/plan/ipv4/net/netv4pooldialog.h \
    mainPanel/menu/plan/ipv4/net/removenetv4dialog.h \
    mainPanel/menu/plan/ipv4/subnet3/mergesubnet3v4dialog.h \
    mainPanel/menu/plan/ipv4/subnet3/splitsubnet3v4dialog.h \
    mainPanel/menu/plan/ipv4/subnet3/subnet3v4assignmentdialog.h \
    mainPanel/menu/plan/ipv4/subnet3/subnet3v4pooldialog.h \
    mainPanel/menu/plan/ipv4/subnet3/subnet3v4releasedialog.h \
    mainPanel/menu/plan/ipv4/subnet1/mergesubnet1v4dialog.h \
    mainPanel/menu/plan/ipv4/subnet1/splitsubnet1v4dialog.h \
    mainPanel/menu/plan/ipv4/subnet1/subnet1v4assignmentdialog.h \
    mainPanel/menu/plan/ipv4/subnet1/subnet1v4pooldialog.h \
    mainPanel/menu/plan/ipv4/subnet1/subnet1v4releasedialog.h \
    mainPanel/menu/plan/ipv4/net/subnetv4searchdialog.h \
    lib/report/exchange/ReportExchange.h \
    mainPanel/menu/plan/vlanRef/addvlanrefdialog.h \
    mainPanel/menu/plan/vlanRef/editvlanrefdialog.h \
    mainPanel/menu/plan/vlanRef/removevlanrefdialog.h \
    mainPanel/menu/plan/vlanRef/vlanrefdialog.h \
    mainPanel/menu/plan/vsiRef/addvsirefdialog.h \
    mainPanel/menu/plan/vsiRef/editvsirefdialog.h \
    mainPanel/menu/plan/vsiRef/removevsirefdialog.h \
    mainPanel/menu/plan/vsiRef/vsirefdialog.h \
    mainPanel/menu/plan/rdRef/addrdrefdialog.h \
    mainPanel/menu/plan/rdRef/editrdrefdialog.h \
    mainPanel/menu/plan/rdRef/rdrefdialog.h \
    mainPanel/menu/plan/rdRef/removerdrefdialog.h \
    mainPanel/menu/plan/pvcRef/addpvcrefdialog.h \
    mainPanel/menu/plan/pvcRef/editpvcrefdialog.h \
    mainPanel/menu/plan/pvcRef/pvcrefdialog.h \
    mainPanel/menu/plan/pvcRef/removepvcrefdialog.h \
    mainPanel/menu/plan/dslam/dslam5616/dslamma5616portdescdialog.h \
    mainPanel/menu/plan/dslam/dslam5600/dslamma5600portdescdialog.h \
    lib/report/general/Report.h \
    mainPanel/menu/plan/dslam/dslammxk819/dslammxk819widget.h \
    mainPanel/menu/plan/dslam/dslammxk819/dslammxk819portdescdialog.h \
    mainPanel/menu/plan/dslam/dslammxk819/mxk819aggmetroplandialog.h \
    mainPanel/menu/plan/dslam/dslammxk819/mxk819singleaggmetroplandialog.h \
    mainPanel/menu/plan/dslam/dslammxk819/mxk819brasplandialog.h \
    mainPanel/menu/plan/dslam/dslammxk819/mxk819singleaggbrasplandialog.h \
    mainPanel/menu/plan/dslam/dslammxk819/mxk819plandialog.h \
    mainPanel/menu/plan/dslam/dslammxk819/mxk819removeaggmetroplandialog.h \
    mainPanel/menu/plan/dslam/dslammxk819/mxk819removebrasplandialog.h \
    mainPanel/menu/plan/dslam/dslammxk819/mxk819removeplandialog.h \
    mainPanel/menu/tools/NetworkAssistant/configWidgets/sysnamewidget.h \
    mainPanel/menu/tools/NetworkAssistant/configWidgets/batchvlanwidget.h \
    mainPanel/menu/tools/NetworkAssistant/configWidgets/vlanwidget.h \
    mainPanel/menu/tools/NetworkAssistant/configWidgets/interfacewidget.h \
    mainPanel/menu/tools/NetworkAssistant/configWidgets/portswitchwidget.h \
    mainPanel/menu/tools/NetworkAssistant/configWidgets/linktypewidget.h \
    mainPanel/menu/tools/NetworkAssistant/configWidgets/trunkwidget.h \
    mainPanel/menu/tools/NetworkAssistant/configWidgets/loadbalacewidget.h \
    mainPanel/menu/tools/NetworkAssistant/configWidgets/allowpasswidget.h \
    mainPanel/menu/tools/NetworkAssistant/configWidgets/defaultvlanwidget.h \
    mainPanel/menu/tools/NetworkAssistant/configWidgets/hybridportwidget.h \
    mainPanel/menu/tools/NetworkAssistant/configWidgets/mapvlanwidget.h \
    mainPanel/menu/tools/NetworkAssistant/configWidgets/ipassignwidget.h \
    mainPanel/menu/tools/NetworkAssistant/configWidgets/bindvpnwidget.h \
    mainPanel/menu/tools/NetworkAssistant/configWidgets/dot1qtagwidget.h \
    mainPanel/menu/tools/NetworkAssistant/configWidgets/qinqwidget.h \
    mainPanel/menu/tools/NetworkAssistant/configWidgets/vpninstancewidget.h \
    mainPanel/menu/tools/NetworkAssistant/configWidgets/routewidget.h \
    mainPanel/deviceWidgets/S9303/s9303widget.h \
    mainPanel/deviceWidgets/S9306/s9306widget.h \
    mainPanel/deviceWidgets/S5300/s5300widget.h \
    mainPanel/deviceWidgets/ME60X16/me60x16widget.h \
    mainPanel/deviceWidgets/ME60X8/me60x8widget.h \
    mainPanel/deviceWidgets/NE5000X16/ne5000X16widget.h \
    mainPanel/deviceWidgets/NE5000X16A/ne5000X16Awidget.h \
    mainPanel/deviceWidgets/NE40X16/ne40x16widget.h \
    mainPanel/deviceWidgets/NE40X8/ne40x8widget.h \
    mainPanel/deviceWidgets/CX200/cx200widget.h \
    mainPanel/deviceWidgets/S2403H/s2403hwidget.h \
    mainPanel/deviceWidgets/ASR9010/asr9010widget.h \
    mainPanel/deviceWidgets/ASR1002/asr1002widget.h \
    mainPanel/deviceWidgets/ASR1013/asr1013widget.h \
    mainPanel/deviceWidgets/C7613/c7613widget.h \
    mainPanel/deviceWidgets/DSLAM16S/dslam16swidget.h \
    mainPanel/deviceWidgets/DSLAM4S/dslam4swidget.h \
    mainPanel/menu/installation/card/odfpinrequestdialog.h \
    mainPanel/menu/installation/device/editdevicedescdialog.h \
    mainPanel/menu/installation/device/editdevicepurchasedialog.h \
    mainPanel/menu/installation/card/changedslamcarddialog.h \
    mainPanel/menu/installation/card/editcarddescdialog.h \
    mainPanel/menu/installation/card/editcardpurchasedialog.h \
    mainPanel/menu/stat/exchangesstatdialog.h \
    mainPanel/menu/stat/portsstatdialog.h \
    mainPanel/menu/stat/cardstatdialog.h \
    mainPanel/menu/plan/dslam/dslamaddnewvlandialog.h \
    mainPanel/menu/report/DSLAM/reporttotaldslamplandialog.h \
    mainPanel/menu/plan/dslam/newSitePlan/newsitedslamdialog.h \
    mainPanel/menu/plan/dslam/localNewDslam/localnewdslamdialog.h \
    mainPanel/menu/stat/devicecountdialog.h \
    mainPanel/menu/stat/devicesstatdialog.h \
    mainPanel/changeinterfaceodfdialog.h \
    mainPanel/OdfAssignDetach/assigninterfaceodfdialog.h \
    mainPanel/OdfAssignDetach/detachinterfaceodfdialog.h \
    mainPanel/menu/installation/card/portbyportodfrequestdialog.h \
    mainPanel/exportexceldialog.h \
    mainPanel/menu/management/saloon/saloonmandialog.h \
    mainPanel/menu/management/saloon/removesaloondialog.h \
    mainPanel/menu/management/saloon/editsaloondialog.h \
    mainPanel/menu/management/saloon/addsaloondialog.h \
    mainPanel/menu/tools/ModuleAnalyser/moduleanalyserdialog.h \
    backbone/startup/outofservice.h \
    mainPanel/menu/installation/device/editdevicenamedialog.h \
    mainPanel/menu/management/interfaceType/addinterfacetypedialog.h \
    mainPanel/menu/management/interfaceType/editinterfacetypedialog.h \
    mainPanel/menu/management/interfaceType/interfacetypedialog.h \
    mainPanel/menu/management/interfaceType/removeinterfacetypedialog.h \
    mainPanel/changeinterfacetypedialog.h \
    mainPanel/menu/help/regexHelp/regexphelpdialog.h \
    mainPanel/menu/plan/dslam/removeDslam/removedslamdialog.h \
    lib/report/DSLAM/RemoveDSLAM.h


FORMS    += \
    backbone/startup/logindialog.ui \
    backbone/startup/newrelease.ui \
    mainPanel/mainpanel.ui \
    mainPanel/menu/admin/users/adduserdialog.ui \
    mainPanel/menu/admin/users/edituserdialog.ui \
    mainPanel/menu/admin/users/removeuserdialog.ui \
    mainPanel/menu/admin/users/usermandialog.ui \
    mainPanel/menu/help/about/aboutdialog2.ui \
    mainPanel/menu/installation/exchangeSite/addexchangesitedialog.ui \
    mainPanel/menu/installation/exchangeSite/editexchangesitedialog.ui \
    mainPanel/menu/installation/exchangeSite/exchangesitemandialog.ui \
    mainPanel/menu/installation/exchangeSite/removeexchangesitedialog.ui \
    mainPanel/menu/installation/ODF/odfmandialog.ui \
    mainPanel/menu/installation/ODF/addodfdialog.ui \
    mainPanel/menu/installation/ODF/removeodfdialog.ui \
    mainPanel/menu/installation/ODF/editodfdialog.ui \
    mainPanel/menu/installation/ODF/addposdialog.ui \
    mainPanel/menu/installation/ODF/removeposdialog.ui \
    mainPanel/menu/installation/ODF/editposnodialog.ui \
    mainPanel/menu/installation/device/deviceinstalldialog.ui \
    mainPanel/menu/installation/device/adddeviceinstalldialog.ui \
    mainPanel/menu/installation/device/removedeviceinstalldialog.ui \
    mainPanel/menu/installation/device/editdevicepositiondialog.ui \
    mainPanel/menu/installation/device/editdevicetypedialog.ui \
    mainPanel/assigninterfacedialog.ui \
    mainPanel/editinterfacedialog.ui \
    mainPanel/emptyinterfacedialog.ui \
    mainPanel/localdevicedialog.ui \
    mainPanel/menu/management/DeviceManagement/addvlandialog.ui \
    mainPanel/menu/management/DeviceManagement/addethertrunkdialog.ui \
    mainPanel/menu/management/DeviceManagement/removevlandialog.ui \
    mainPanel/menu/management/DeviceManagement/removeethertrunkdialog.ui \
    mainPanel/menu/management/DeviceManagement/editvlandialog.ui \
    mainPanel/menu/management/DeviceManagement/editethertrunkdialog.ui \
    mainPanel/menu/management/DeviceManagement/devicemanagementdialog.ui \
    mainPanel/menu/management/ODFManagement/odfmanagementdialog.ui \
    mainPanel/menu/management/ODFManagement/assignodfpindialog.ui \
    mainPanel/menu/management/ODFManagement/editodfpindialog.ui \
    mainPanel/menu/management/ODFManagement/depleteodfpindialog.ui \
    mainPanel/menu/management/DeviceManagement/addvpndialog.ui \
    mainPanel/menu/management/DeviceManagement/editvpndialog.ui \
    mainPanel/menu/management/DeviceManagement/removevpndialog.ui \
    mainPanel/menu/management/commodities/cat/cat_addedit.ui \
    mainPanel/menu/management/commodities/cat/cat_dialog.ui \
    mainPanel/menu/management/commodities/commodity/comm_dialog.ui \
    mainPanel/menu/management/commodities/commodity/comm_addedit.ui \
    mainPanel/menu/management/commodities/commodity/comm_remove.ui \
    mainPanel/menu/management/commodities/cat/cat_remove.ui \
    mainPanel/menu/management/commodities/usage/usage_addedit.ui \
    mainPanel/menu/management/commodities/usage/usage_dialog.ui \
    mainPanel/menu/management/commodities/usage/usage_remove.ui \
    mainPanel/menu/management/letters/letteraddeditdialog.ui \
    mainPanel/menu/management/letters/letterremovedialog.ui \
    mainPanel/menu/management/letters/lettersdialog.ui \
    mainPanel/menu/management/letters/letterviewdialog.ui \
    mainPanel/menu/management/purchases/purchasemandialog.ui \
    mainPanel/menu/management/purchases/addpurchasedialog.ui \
    mainPanel/menu/management/purchases/editpurchasedialog.ui \
    mainPanel/menu/management/purchases/removepurchasedialog.ui \
    mainPanel/menu/management/devices/adddevicedialog.ui \
    mainPanel/menu/management/devices/devicemandialog.ui \
    mainPanel/menu/management/devices/editdevicedialog.ui \
    mainPanel/menu/management/devices/removedevicedialog.ui \
    mainPanel/menu/management/cards/addcarddialog.ui \
    mainPanel/menu/management/cards/cardmandialog.ui \
    mainPanel/menu/management/cards/editcarddialog.ui \
    mainPanel/menu/management/cards/removecarddialog.ui \
    mainPanel/menu/management/telephones/telephoneaddeditdialog.ui \
    mainPanel/menu/management/telephones/telephoneremovedialog.ui \
    mainPanel/menu/management/telephones/telephonesdialog.ui \
    mainPanel/menu/management/telephones/telephoneviewdialog.ui \
    mainPanel/menu/management/uninstalled/uninstalledaddeditdialog.ui \
    mainPanel/menu/management/uninstalled/uninstalleddialog.ui \
    mainPanel/menu/management/uninstalled/uninstalledremovedialog.ui \
    mainPanel/menu/plan/ipv4/subnet2/subnet2v4pooldialog.ui \
    mainPanel/menu/plan/ipv4/subnet2/subnet2v4assignmentdialog.ui \
    mainPanel/menu/plan/ipv4/subnet2/subnet2v4releasedialog.ui \
    mainPanel/menu/plan/ipv4/ip/ipv4pooldialog.ui \
    mainPanel/menu/plan/ipv4/ip/ipv4assigndialog.ui \
    mainPanel/menu/plan/ipv4/ip/ipv4releasedialog.ui \
    mainPanel/menu/plan/ipv4/ip/addipv4pooldialog.ui \
    mainPanel/menu/plan/ipv4/ip/removeipv4pooldialog.ui \
    mainPanel/menu/plan/connection/editbrasaggdialog.ui \
    mainPanel/menu/plan/connection/removebrasaggdialog.ui \
    mainPanel/menu/plan/connection/addbrasaggdialog.ui \
    mainPanel/menu/plan/connection/connectiondialog.ui \
    mainPanel/menu/plan/connection/addaggcxdialog.ui \
    mainPanel/menu/plan/connection/editaggcxdialog.ui \
    mainPanel/menu/plan/connection/removeaggcxdialog.ui \
    mainPanel/menu/plan/dslam/dslamdialog.ui \
    mainPanel/menu/plan/dslam/dslam5600/dslamma5600widget.ui \
    mainPanel/menu/plan/dslam/dslam5616/dslamma5616widget.ui \
    mainPanel/menu/plan/dslam/dslam5600/ma5600plandialog.ui \
    mainPanel/menu/plan/dslam/dslam5600/ma5600brasplandialog.ui \
    mainPanel/menu/plan/dslam/dslam5600/ma5600singleaggbrasplandialog.ui \
    mainPanel/menu/plan/dslam/dslam5600/ma5600removeplandialog.ui \
    mainPanel/menu/plan/dslam/dslam5600/ma5600aggmetroplandialog.ui \
    mainPanel/menu/plan/dslam/dslam5600/ma5600singleaggmetroplandialog.ui \
    mainPanel/menu/plan/dslam/dslam5600/ma5600removeaggmetroplandialog.ui \
    mainPanel/menu/plan/dslam/dslam5600/ma5600removebrasplandialog.ui \
    mainPanel/menu/plan/dslam/dslam5616/ma5616plandialog.ui \
    mainPanel/menu/plan/dslam/dslam5616/ma5616removeplandialog.ui \
    mainPanel/menu/plan/dslam/dslam5616/ma5616removeaggmetroplandialog.ui \
    mainPanel/menu/plan/dslam/dslam5616/ma5616removebrasplandialog.ui \
    mainPanel/menu/plan/dslam/dslam5616/ma5616aggmetroplandialog.ui \
    mainPanel/menu/plan/dslam/dslam5616/ma5616brasplandialog.ui \
    mainPanel/menu/plan/dslam/dslam5616/ma5616singleaggbrasplandialog.ui \
    mainPanel/menu/management/modules/editmodulesdialog.ui \
    mainPanel/menu/management/modules/removemoduledialog.ui \
    mainPanel/menu/management/modules/modulesmandialog.ui \
    mainPanel/menu/management/modules/addmoduledialog.ui \
    mainPanel/menu/plan/accessSingleSwitch/accesssingleswitchdialog.ui \
    mainPanel/menu/plan/accessDoubleSwitch/accessdoubleswitchdialog.ui \
    mainPanel/menu/plan/accessBrasConfig/accessbrasconfigdialog.ui \
    mainPanel/menu/plan/NAS/brasnasipmandialog.ui \
    mainPanel/menu/plan/NAS/editnasipdialog.ui \
    mainPanel/menu/plan/NAS/removenasipdialog.ui \
    mainPanel/menu/plan/NAS/addnasipdialog.ui \
    mainPanel/menu/installation/card/cardinstalldialog.ui \
    mainPanel/menu/installation/card/adddevicecarddialog.ui \
    mainPanel/menu/installation/card/removedevicecarddialog.ui \
    mainPanel/changemoduledialog.ui \
    mainPanel/menu/plan/SBCIpLB/sbciploopbackdialog.ui \
    mainPanel/exchangeinfodialog.ui \
    mainPanel/menu/report/interface/interfacereportdialog.ui \
    mainPanel/menu/report/lom/lomitemdialog.ui \
    mainPanel/menu/report/odf/odfreportdialog.ui \
    mainPanel/exportpdfdialog.ui \
    mainPanel/menu/plan/commercial/reservetocommercialdialog.ui \
    mainPanel/menu/report/sites/exchangesitesreportdialog.ui \
    mainPanel/menu/report/floorplan/floorplanreportdialog.ui \
    mainPanel/menu/report/device/reportdevicedialog.ui \
    mainPanel/menu/report/ipv4plan/net/reportnetworkv4dialog.ui \
    mainPanel/menu/report/ipv4plan/subnet/reportsubnetv4dialog.ui \
    mainPanel/menu/report/ipv4plan/ip/reportipv4dialog.ui \
    mainPanel/menu/tools/NetworkCalculator/networkcalculatordialog.ui \
    mainPanel/menu/report/DSLAM/reportdslamdialog.ui \
    mainPanel/menu/tools/ipPoolAnalyser/ippoolanalyserdialog.ui \
    mainPanel/menu/tools/ConfigurationAnalyser/configurationanalyserdialog.ui \
    mainPanel/menu/tools/NetworkAssistant/networkassistantdialog.ui \
    mainPanel/menu/log/recentLog/recentlogdialog.ui \
    mainPanel/menu/profile/profiledialog.ui \
    mainPanel/menu/help/about/aboutdialog.ui \
    mainPanel/menu/help/recommendation/recommendationdialog.ui \
    mainPanel/menu/admin/recommendations/recommendationsviewdialog.ui \
    mainPanel/menu/admin/recommendations/removerecommendationdialog.ui \
    mainPanel/menu/report/commercial/reportreservetocommercialdialog.ui \
    mainPanel/menu/admin/log/clearlogdialog.ui \
    mainPanel/menu/report/lom/lomdialog.ui \
    mainPanel/menu/plan/ipv4/subnet2/splitsubnet2v4dialog.ui \
    mainPanel/menu/plan/ipv4/subnet2/mergesubnet2v4dialog.ui \
    mainPanel/menu/plan/ipv4/net/netv4pooldialog.ui \
    mainPanel/menu/plan/ipv4/net/addnetv4dialog.ui \
    mainPanel/menu/plan/ipv4/net/editnetv4dialog.ui \
    mainPanel/menu/plan/ipv4/net/removenetv4dialog.ui \
    mainPanel/menu/plan/ipv4/net/netv4assignmentdialog.ui \
    mainPanel/menu/plan/ipv4/subnet3/mergesubnet3v4dialog.ui \
    mainPanel/menu/plan/ipv4/subnet3/splitsubnet3v4dialog.ui \
    mainPanel/menu/plan/ipv4/subnet3/subnet3v4assignmentdialog.ui \
    mainPanel/menu/plan/ipv4/subnet3/subnet3v4pooldialog.ui \
    mainPanel/menu/plan/ipv4/subnet3/subnet3v4releasedialog.ui \
    mainPanel/menu/plan/ipv4/subnet1/mergesubnet1v4dialog.ui \
    mainPanel/menu/plan/ipv4/subnet1/splitsubnet1v4dialog.ui \
    mainPanel/menu/plan/ipv4/subnet1/subnet1v4assignmentdialog.ui \
    mainPanel/menu/plan/ipv4/subnet1/subnet1v4pooldialog.ui \
    mainPanel/menu/plan/ipv4/subnet1/subnet1v4releasedialog.ui \
    mainPanel/menu/plan/ipv4/net/subnetv4searchdialog.ui \
    mainPanel/menu/plan/vlanRef/addvlanrefdialog.ui \
    mainPanel/menu/plan/vlanRef/editvlanrefdialog.ui \
    mainPanel/menu/plan/vlanRef/removevlanrefdialog.ui \
    mainPanel/menu/plan/vlanRef/vlanrefdialog.ui \
    mainPanel/menu/plan/vsiRef/addvsirefdialog.ui \
    mainPanel/menu/plan/vsiRef/editvsirefdialog.ui \
    mainPanel/menu/plan/vsiRef/removevsirefdialog.ui \
    mainPanel/menu/plan/vsiRef/vsirefdialog.ui \
    mainPanel/menu/plan/rdRef/addrdrefdialog.ui \
    mainPanel/menu/plan/rdRef/editrdrefdialog.ui \
    mainPanel/menu/plan/rdRef/rdrefdialog.ui \
    mainPanel/menu/plan/rdRef/removerdrefdialog.ui \
    mainPanel/menu/plan/pvcRef/addpvcrefdialog.ui \
    mainPanel/menu/plan/pvcRef/editpvcrefdialog.ui \
    mainPanel/menu/plan/pvcRef/pvcrefdialog.ui \
    mainPanel/menu/plan/pvcRef/removepvcrefdialog.ui \
    mainPanel/menu/plan/dslam/dslam5616/dslamma5616portdescdialog.ui \
    mainPanel/menu/plan/dslam/dslam5600/dslamma5600portdescdialog.ui \
    mainPanel/menu/plan/dslam/dslammxk819/dslammxk819widget.ui \
    mainPanel/menu/plan/dslam/dslammxk819/dslammxk819portdescdialog.ui \
    mainPanel/menu/plan/dslam/dslammxk819/mxk819aggmetroplandialog.ui \
    mainPanel/menu/plan/dslam/dslammxk819/mxk819singleaggmetroplandialog.ui \
    mainPanel/menu/plan/dslam/dslammxk819/mxk819brasplandialog.ui \
    mainPanel/menu/plan/dslam/dslammxk819/mxk819singleaggbrasplandialog.ui \
    mainPanel/menu/plan/dslam/dslammxk819/mxk819plandialog.ui \
    mainPanel/menu/plan/dslam/dslammxk819/mxk819removeaggmetroplandialog.ui \
    mainPanel/menu/plan/dslam/dslammxk819/mxk819removebrasplandialog.ui \
    mainPanel/menu/plan/dslam/dslammxk819/mxk819removeplandialog.ui \
    mainPanel/menu/tools/NetworkAssistant/configWidgets/sysnamewidget.ui \
    mainPanel/menu/tools/NetworkAssistant/configWidgets/batchvlanwidget.ui \
    mainPanel/menu/tools/NetworkAssistant/configWidgets/vlanwidget.ui \
    mainPanel/menu/tools/NetworkAssistant/configWidgets/interfacewidget.ui \
    mainPanel/menu/tools/NetworkAssistant/configWidgets/portswitchwidget.ui \
    mainPanel/menu/tools/NetworkAssistant/configWidgets/linktypewidget.ui \
    mainPanel/menu/tools/NetworkAssistant/configWidgets/trunkwidget.ui \
    mainPanel/menu/tools/NetworkAssistant/configWidgets/loadbalacewidget.ui \
    mainPanel/menu/tools/NetworkAssistant/configWidgets/allowpasswidget.ui \
    mainPanel/menu/tools/NetworkAssistant/configWidgets/defaultvlanwidget.ui \
    mainPanel/menu/tools/NetworkAssistant/configWidgets/hybridportwidget.ui \
    mainPanel/menu/tools/NetworkAssistant/configWidgets/mapvlanwidget.ui \
    mainPanel/menu/tools/NetworkAssistant/configWidgets/ipassignwidget.ui \
    mainPanel/menu/tools/NetworkAssistant/configWidgets/bindvpnwidget.ui \
    mainPanel/menu/tools/NetworkAssistant/configWidgets/dot1qtagwidget.ui \
    mainPanel/menu/tools/NetworkAssistant/configWidgets/qinqwidget.ui \
    mainPanel/menu/tools/NetworkAssistant/configWidgets/vpninstancewidget.ui \
    mainPanel/menu/tools/NetworkAssistant/configWidgets/routewidget.ui \
    mainPanel/deviceWidgets/S9303/s9303widget.ui \
    mainPanel/deviceWidgets/S9306/s9306widget.ui \
    mainPanel/deviceWidgets/S5300/s5300widget.ui \
    mainPanel/deviceWidgets/ME60X16/me60x16widget.ui \
    mainPanel/deviceWidgets/ME60X8/me60x8widget.ui \
    mainPanel/deviceWidgets/NE5000X16/ne5000X16widget.ui \
    mainPanel/deviceWidgets/NE5000X16A/ne5000X16Awidget.ui \
    mainPanel/deviceWidgets/NE40X16/ne40x16widget.ui \
    mainPanel/deviceWidgets/NE40X8/ne40x8widget.ui \
    mainPanel/deviceWidgets/CX200/cx200widget.ui \
    mainPanel/deviceWidgets/S2403H/s2403hwidget.ui \
    mainPanel/deviceWidgets/ASR9010/asr9010widget.ui \
    mainPanel/deviceWidgets/ASR1002/asr1002widget.ui \
    mainPanel/deviceWidgets/ASR1013/asr1013widget.ui \
    mainPanel/deviceWidgets/C7613/c7613widget.ui \
    mainPanel/deviceWidgets/DSLAM16S/dslam16swidget.ui \
    mainPanel/deviceWidgets/DSLAM4S/dslam4swidget.ui \
    mainPanel/menu/installation/card/odfpinrequestdialog.ui \
    mainPanel/menu/installation/device/editdevicedescdialog.ui \
    mainPanel/menu/installation/device/editdevicepurchasedialog.ui \
    mainPanel/menu/installation/card/changedslamcarddialog.ui \
    mainPanel/menu/installation/card/editcarddescdialog.ui \
    mainPanel/menu/installation/card/editcardpurchasedialog.ui \
    mainPanel/menu/stat/exchangesstatdialog.ui \
    mainPanel/menu/stat/portsstatdialog.ui \
    mainPanel/menu/stat/cardstatdialog.ui \
    mainPanel/menu/plan/dslam/dslamaddnewvlandialog.ui \
    mainPanel/menu/report/DSLAM/reporttotaldslamplandialog.ui \
    mainPanel/menu/plan/dslam/localNewDslam/localnewdslamdialog.ui \
    mainPanel/menu/stat/devicecountdialog.ui \
    mainPanel/menu/stat/devicesstatdialog.ui \
    mainPanel/changeinterfaceodfdialog.ui \
    mainPanel/OdfAssignDetach/assigninterfaceodfdialog.ui \
    mainPanel/OdfAssignDetach/detachinterfaceodfdialog.ui \
    mainPanel/menu/installation/card/portbyportodfrequestdialog.ui \
    mainPanel/exportexceldialog.ui \
    mainPanel/menu/management/saloon/saloonmandialog.ui \
    mainPanel/menu/management/saloon/removesaloondialog.ui \
    mainPanel/menu/management/saloon/editsaloondialog.ui \
    mainPanel/menu/management/saloon/addsaloondialog.ui \
    mainPanel/menu/tools/ModuleAnalyser/moduleanalyserdialog.ui \
    backbone/startup/outofservice.ui \
    mainPanel/menu/installation/device/editdevicenamedialog.ui \
    mainPanel/menu/management/interfaceType/addinterfacetypedialog.ui \
    mainPanel/menu/management/interfaceType/editinterfacetypedialog.ui \
    mainPanel/menu/management/interfaceType/interfacetypedialog.ui \
    mainPanel/menu/management/interfaceType/removeinterfacetypedialog.ui \
    mainPanel/changeinterfacetypedialog.ui \
    mainPanel/menu/help/regexHelp/regexphelpdialog.ui \
    mainPanel/menu/plan/dslam/removeDslam/removedslamdialog.ui


RESOURCES += \
    configurations.qrc \
    image.qrc \
    font.qrc \
    qml.qrc

RC_ICONS = danet.ico

